name: Package

permissions:
  contents: read # access to check out code and install dependencies

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - run: bun clear
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Format
        run: bun run -b format
      - name: Lint
        run: bun run -b lint
      - run: bun clear

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - run: bun clear
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Test
        run: bun run -b test
      - run: bun clear

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - run: bun clear
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Dev Build
        run: bun run -b dev:build
      - run: bun clear

  pack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - run: bun clear
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Bun Pack
        run: bun pm pack
      - run: bun clear
