name: Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Lint
        run: bunrun lint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Playground prepare
        run: bun run dev:prepare
      - name: Test
        run: bun run test

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Build without Bun runtime
        run: bun run dev:build
      - name: Build without Bun runtime
        run: bun run -b dev:build
      - name: NPM Publish dry run
        run: bun pm publish --dry-run
